import Head from 'next/head'
import Image from 'next/image'
import { Featured } from '../components/Featured'
import { PizzaList } from '../components/PizzaList'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'
import { AddButton } from '../components/AddButton'
import { Add } from '../components/Add'

export default function Home({ pizzaList, admin }) {
  const [close, setClose] = useState(true);
  return (
    <div className={styles.container}>
      <Head>
        <title>Pizza Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/** SLIDER */}
      <Featured/>
      {<AddButton setClose={setClose} />}
      {/** Pizza List */}
      <PizzaList pizzaList={pizzaList}/>
      {!close && (<Add setClose={setClose}/>) }
    </div>
  )
}

export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || '';
  let admin = false;

  if(myCookie.token === process.env.TOKEN) {
    admin = true;
  }

  const res = await axios.get('http://localhost:3000/api/products');
  return {
    props: {
      pizzaList: res.data,
      admin: admin
    }
  }
}